version: '3'
services:
  #web:
  #略
  mongo:
    image: mongo:6.0.6
    environment:
      - AUTH=no
    command: [--replSet, my-replica-set, --noauth, --bind_ip_all]
    ports:
      - 27017:27017
    healthcheck:
      test: mongosh mongo-init.js
      interval: 10s
      start_period: 30s
    volumes:
      - mongodb_data:/data/db
      - ./mongodb/init/mongo-init.js:/mongo-init.js
    restart: always
  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - 8081:8081
    environment:
      #ME_CONFIG_MONGODB_URL: mongodb://@mongo:27017/
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin # mongo-expressアクセス時に要求されるユーザー名。なくてもOK。
      ME_CONFIG_BASICAUTH_PASSWORD: Tmhr1582
    depends_on:
      - mongo
# mongodbのデータはdocker volumeで管理されるので、消すときは docker volume rm mongodb_data
volumes:
  mongodb_data:
