version: '3'
services:
  mongo:
    build: 
      context: ./mongodb
      dockerfile: Dockerfile
  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin # mongo-expressアクセス時に要求されるユーザー名。なくてもOK。
      ME_CONFIG_BASICAUTH_PASSWORD: Tmhr1582
    depends_on:
      - mongo
  # pubsub:
  #   build: 
  #     context: ./pubsub
  #     dockerfile: Dockerfile
  #   restart: always
  #   environment:
  #     - PROJECT_ID=emulator
  #     - TOPIC_ID=event-topic-local
  #     - SUBSCRIPTION_ID=event-subscription-local
  #     - PUSH_ENDPOINT=http://host.docker.internal:3000/example
  #   extra_hosts:
  #     - host.docker.internal:host-gateway
  #   ports:
  #     - 8085:8085
# mongodbのデータはdocker volumeで管理されるので、消すときは docker volume rm mongodb_data
volumes:
  mongodb_data:
